export interface Portfolio {
    "id": number,
    "usuario":string,
    "ativo": string,
    "cotacao": number,
    "meta": number,
    "porcentagem":number,
    "variacaoAnual":number,
    "quantidade": number,
    "status": string,
    "tipo": string,
    "valor": number,
    "aporte":number,
    "comentarios": string,
    "precoMedio":number,
    "valuation":number,
    "dy":number,
    "valuationDFC":number,
}
