# Generated by Django 5.0.6 on 2024-06-06 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PortfolioModels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ativo', models.CharField(max_length=250, unique=True)),
                ('cotacao', models.FloatField(blank=True, null=True)),
                ('porcentagem', models.FloatField(blank=True, null=True)),
                ('meta', models.FloatField(blank=True, null=True)),
                ('quantidade', models.IntegerField(blank=True, default=0, null=True)),
                ('status', models.CharField(choices=[('comprar', 'comprar'), ('aguardar', 'aguardar'), ('vender', 'vender')], default='comprar', max_length=250)),
                ('tipo', models.CharField(choices=[('acao', 'acao'), ('bdr', 'bdr'), ('fii', 'fii'), ('rendaFixa', 'rendaFixa')], max_length=250)),
                ('valor', models.FloatField(blank=True, default=0, null=True)),
                ('aporte', models.IntegerField(blank=True, default=0, null=True)),
                ('comentarios', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
