# Generated by Django 5.0.6 on 2024-06-05 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioAPI', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfoliomodels',
            name='aporte',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='portfoliomodels',
            name='comentarios',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='portfoliomodels',
            name='cotacao',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='portfoliomodels',
            name='meta',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='portfoliomodels',
            name='quantidade',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='portfoliomodels',
            name='valor',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
