# Generated by Django 5.0.6 on 2024-07-06 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioAPI', '0002_alter_portfoliomodels_quantidade'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfoliomodels',
            name='variacaoAnual',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
