# Generated by Django 5.0.6 on 2024-12-06 11:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioAPI', '0002_alter_portfoliomodels_unique_together_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfoliomodels',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='portfoliomodels',
            constraint=models.UniqueConstraint(fields=('usuario', 'ativo'), name='unique_portfolio_per_user'),
        ),
    ]
