# Generated by Django 5.0.6 on 2024-06-05 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioAPI', '0002_alter_portfoliomodels_aporte_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfoliomodels',
            name='porcentagem',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
