# Generated by Django 5.0.6 on 2024-12-10 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioAPI', '0004_alter_portfoliomodels_ativo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfoliomodels',
            name='cotacao',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
