# Generated by Django 5.0.6 on 2024-12-10 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioAPI', '0006_alter_portfoliomodels_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfoliomodels',
            name='scoreQualitativo',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
