# Generated by Django 5.0.6 on 2024-12-02 21:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioAPI', '0007_portfoliomodels_valuationdfc'),
    ]

    operations = [
        migrations.RenameField(
            model_name='portfoliomodels',
            old_name='valuation',
            new_name='valuationDy',
        ),
    ]
