# Generated by Django 5.0.6 on 2024-12-10 21:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioAPI', '0007_portfoliomodels_scorequalitativo'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionarioQualitativoForms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question00', models.CharField(blank=True, max_length=10, null=True)),
                ('question01', models.CharField(blank=True, max_length=10, null=True)),
                ('question02', models.CharField(blank=True, max_length=10, null=True)),
                ('question03', models.CharField(blank=True, max_length=10, null=True)),
                ('question04', models.CharField(blank=True, max_length=10, null=True)),
                ('question05', models.CharField(blank=True, max_length=10, null=True)),
                ('question06', models.CharField(blank=True, max_length=10, null=True)),
                ('question07', models.CharField(blank=True, max_length=10, null=True)),
                ('question08', models.CharField(blank=True, max_length=10, null=True)),
                ('question09', models.CharField(blank=True, max_length=10, null=True)),
                ('question010', models.CharField(blank=True, max_length=10, null=True)),
                ('question011', models.CharField(blank=True, max_length=10, null=True)),
                ('ativo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolioAPI.portfoliomodels')),
            ],
        ),
    ]
