# Generated by Django 5.0.6 on 2024-12-10 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioAPI', '0008_questionarioqualitativoforms'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionarioqualitativoforms',
            name='question00',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='questionarioqualitativoforms',
            name='question01',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='questionarioqualitativoforms',
            name='question010',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='questionarioqualitativoforms',
            name='question011',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='questionarioqualitativoforms',
            name='question02',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='questionarioqualitativoforms',
            name='question03',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='questionarioqualitativoforms',
            name='question04',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='questionarioqualitativoforms',
            name='question05',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='questionarioqualitativoforms',
            name='question06',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='questionarioqualitativoforms',
            name='question07',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='questionarioqualitativoforms',
            name='question08',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='questionarioqualitativoforms',
            name='question09',
            field=models.FloatField(default=0),
        ),
    ]
