# Generated by Django 5.0.6 on 2024-12-11 00:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolioAPI', '0010_portfoliomodels_question00_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='portfoliomodels',
            old_name='question00',
            new_name='question0',
        ),
        migrations.RenameField(
            model_name='portfoliomodels',
            old_name='question01',
            new_name='question1',
        ),
        migrations.RenameField(
            model_name='portfoliomodels',
            old_name='question02',
            new_name='question2',
        ),
        migrations.RenameField(
            model_name='portfoliomodels',
            old_name='question03',
            new_name='question3',
        ),
        migrations.RenameField(
            model_name='portfoliomodels',
            old_name='question04',
            new_name='question4',
        ),
        migrations.RenameField(
            model_name='portfoliomodels',
            old_name='question05',
            new_name='question5',
        ),
        migrations.RenameField(
            model_name='portfoliomodels',
            old_name='question06',
            new_name='question6',
        ),
        migrations.RenameField(
            model_name='portfoliomodels',
            old_name='question07',
            new_name='question7',
        ),
        migrations.RenameField(
            model_name='portfoliomodels',
            old_name='question08',
            new_name='question8',
        ),
        migrations.RenameField(
            model_name='portfoliomodels',
            old_name='question09',
            new_name='question9',
        ),
    ]
